In [1]:
import numpy as np

In [2]:
Q = np.random.randn(6,6)
A = (Q+Q.T)/2 # standard trick to get symmetric matrix when Q is real
print(A)
eigenvalues, eigenvectors = np.linalg.eigh(A) #Special routine for hermitian matrix. Real+symmetric -> Hermitian
print(eigenvalues)
print(eigenvectors)

[[-0.05283497  0.02866041  0.63468376 -0.57481841  1.19686649 -0.08500131]
 [ 0.02866041 -0.847094   -0.53328017 -0.25154654 -0.18814754 -0.34802783]
 [ 0.63468376 -0.53328017  1.8713782   1.13351469 -0.12907365 -1.24379992]
 [-0.57481841 -0.25154654  1.13351469 -0.28900251  0.205553   -0.70243932]
 [ 1.19686649 -0.18814754 -0.12907365  0.205553    0.9610403  -0.69423775]
 [-0.08500131 -0.34802783 -1.24379992 -0.70243932 -0.69423775  0.87211488]]
[-1.68028956 -1.21662601 -0.18977211  0.46763252  1.74945502  3.38520203]
[[-0.60144543  0.16344776  0.36306643  0.46454213 -0.48317079  0.17457831]
 [ 0.28570696  0.77485452  0.47557069 -0.28937991 -0.04289742 -0.07888989]
 [ 0.37908108  0.06568328  0.08740517  0.44565347  0.3120539   0.74051261]
 [-0.47265651  0.48972347 -0.58236893 -0.23002917  0.20988376  0.31725159]
 [ 0.39582864  0.04813451 -0.40471812 -0.09071371 -0.78588374  0.22663577]
 [ 0.18124009  0.35556295 -0.36252627  0.66386028  0.07525768 -0.5127646 ]]


In [3]:
test_eigenvalues = np.diag(np.linalg.inv(eigenvectors) @ A @ eigenvectors) # D = P^-1 @ A @ P
print(test_eigenvalues-eigenvalues)

[-4.44089210e-16 -2.22044605e-16 -4.99600361e-16 -5.55111512e-17
 -1.11022302e-15 -1.77635684e-15]


In [4]:
test_matrix = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors) # A = P @ D @ P^(-1)
print(A-test_matrix)

[[-2.15105711e-16  6.93889390e-17 -3.33066907e-16 -2.22044605e-16
  -6.66133815e-16  8.32667268e-17]
 [ 2.60208521e-16 -8.88178420e-16  8.88178420e-16  1.27675648e-15
   1.94289029e-16 -1.11022302e-15]
 [ 5.55111512e-16 -5.55111512e-16 -1.33226763e-15 -8.88178420e-16
   7.49400542e-16  1.11022302e-15]
 [-3.33066907e-16  8.32667268e-16 -1.11022302e-15 -7.21644966e-16
  -3.33066907e-16  9.99200722e-16]
 [ 4.44089210e-16 -1.11022302e-16  1.11022302e-15  5.27355937e-16
   1.11022302e-16 -3.33066907e-16]
 [-2.77555756e-17 -3.33066907e-16  1.11022302e-15  8.88178420e-16
  -2.22044605e-16 -1.33226763e-15]]


In [5]:
# Use method of Yi et all to compute and compare the above eigenvalues/vectors.