In [10]:
import numpy as np

In [11]:
x = np.random.randn(3, 5)
x = np.ones([3, 5]) ;x[1, :] *= 2; x[2, :] *= 3
print(x.shape)
print(x)

(3, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]


In [12]:
y = np.random.randn(5)
y = np.zeros(5)
print(y.shape)
print(y)

(5,)
[0. 0. 0. 0. 0.]


In [13]:
sub = y - x
print(sub.shape)
print(sub)

(3, 5)
[[-1. -1. -1. -1. -1.]
 [-2. -2. -2. -2. -2.]
 [-3. -3. -3. -3. -3.]]


In [14]:
mean_x = np.mean(x, axis=1, keepdims=True)
print(mean_x)

[[1.]
 [2.]
 [3.]]


In [15]:
(y - mean_x) ** 2

array([[1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4.],
       [9., 9., 9., 9., 9.]])

In [16]:
np.mean(np.sum((y - mean_x) ** 2, axis=1) / len(y))

4.666666666666667

In [17]:
x[0, 3] = 51
x[0, 2] = 21
x

array([[ 1.,  1., 21., 51.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.]])

In [25]:
np.var(x, axis = 1, keepdims=True)

array([[384.],
       [  0.],
       [  0.]])

In [32]:
np.mean(y - x, axis=1, keepdims=True)

array([[-15.],
       [ -2.],
       [ -3.]])