In [10]:
import autograd.numpy as np
import matplotlib.pyplot
from autograd import grad, elementwise_grad, hessian, jacobian

import sys
sys.path.insert(0, "../../project_2/src")
from SGD import minibatch

In [202]:
# Inspired by mortens example code in week 43

def activation_function(z):
    return np.maximum(0, z)

def activation_out(z):
    return z

"""
network_shape = [inputs, w1, w2, ..., wL, outputs]

W = wwwwb
    wwwwb
"""
def initialize_params(network_shape):
    P = []
    for i in range(1, len(network_shape)):
        k = network_shape[i-1]
        j = network_shape[i]
        P.append(np.random.randn(j, k) * np.sqrt(2) / np.sqrt(k))
        P[i-1] = np.concatenate((P[i-1], np.zeros(j).reshape(-1,1)), axis=1)

    return P

def Network(x, P):
    a = x
    for P_i in P:
        a = np.concatenate((a, np.ones(np.size(a, 0)).reshape(-1, 1)), axis=1) 
        print("a ->", a.shape)
        print("P ->", P_i.shape)
        z = np.matmul(a, np.transpose(P_i))
        a = activation_function(z)
    
    return activation_out(z)

def optimize(X, P, N_minibatches, learning_rate, n_epochs):
    
    assert N_minibatches <= np.size(X, 0)

    cost_func_grad = grad(costfunction, 1)
    
    for epoch in range(n_epochs):
        mb = minibatch(X, N_minibatches)
        for i in range(N_minibatches):
            X_mb = X[mb[i]]
            M = np.size(X_mb, 0)
            # compute gradients of weights
            cost_grad = cost_func_grad(X_mb, P)
            
            for l in range(len(P)):
                P[l] -= - learning_rate * cost_grad[l]
    return P

def g_trial(x, P):
    return (1 - x[1]) * np.sin(np.pi * x[0]) + x[0] * (1 - x[0]) * x[1] * Network(x, P)

def costfunction(x, P):
    cost = 0
    u_hess = hessian(g_trial)
    u_jacob = jacobian(g_trial)
    
    for point in x:
        dudx2 = u_hess(point, P)[0,0]
        dudt = u_jacob(point, P)[1]
        cost += (dudt - dudx2)**2

    return cost / np.size(x, 0)

In [160]:
x = np.linspace(0,1,10)
t = np.linspace(0,1,10)
x, t = np.meshgrid(x, t) 
x = x.flatten()
t = t.flatten()
X = np.concatenate((x.reshape(-1,1), t.reshape(-1, 1)), axis=1)

network_shape = [np.size(X, 1), 10, 1]
P = initialize_params(network_shape)

In [213]:
P = optimize(X, P, 10, 0.002, 10)
#y = Network(X[0, :].reshape(1, 2), P)

AxisError: axis 1 is out of bounds for array of dimension 1

In [216]:
np.array([X[0, :], 0])

array([array([0., 0.]), array(0)], dtype=object)

In [128]:
# network_shape = [inputs, w1, w2, ..., wL, outputs]
def initialize_params(network_shape):
    P = []
    for i in range(1, len(network_shape)):
        k = network_shape[i-1]
        j = network_shape[i]
        print(i, "->", f"k={k}", f"j={j}")
        P.append(np.random.randn(j, k) * np.sqrt(2) / np.sqrt(k))
        P[i-1] = np.concatenate((P[i-1], np.zeros(j).reshape(-1,1)), axis=1)
    
    return P

P = initialize_params([2, 3, 1])
print(P[0])
print(P[1])

#X_i = [x, t, 1]

1 -> k=2 j=3
2 -> k=3 j=1
[[ 1.53955784 -0.65574862  0.        ]
 [-0.25409971 -1.06275851  0.        ]
 [-1.2672916  -0.99436508  0.        ]]
[[-1.03736743 -0.64167878  0.18840454  0.        ]]


In [117]:
k = 2
j = 4

P = np.zeros([j,k])
print(P)
b = np.ones(j).reshape(-1, 1)
print(b)
P = np.concatenate((P, b), axis=1)
print(P)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1.]
 [1.]
 [1.]
 [1.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
